apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "sleep", "3600" ]
    volumeMounts:
    - name: migrations
      mountPath: /mnt/migrations
  volumes:
  - name: migrations
    persistentVolumeClaim:
      claimName: migrations-pvc
  restartPolicy: Never
